theme: jekyll-theme-minimal
title: Pierre Baduel
google_analytics: UA-59172984-3
twitter_username: pierrebaduel
linkedin_username: pierre-baduel-2b5280105
timezone: Europe/Paris
future: true
logo: /images/Logo-publi.png
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-twitter-plugin
