theme: jekyll-theme-minimal
title: Pierre Baduel
description: Polyploidy, Epigenetics & Transposable Elements @<a href="https://www.ibens.ens.fr/?lang=en">IBENS</a>
google_analytics: G-TS2FHR25CT
twitter_username: pierrebaduel
linkedin_username: pierre-baduel-2b5280105
timezone: Europe/Paris
future: true
logo: /images/logos_IBENS_ENS_PSL.png
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-twitter-plugin
